nmshd/runtime

package-lock.json
packages/runtime/package.json
packages/runtime/src/events/EventProxy.ts
packages/runtime/src/events/transport/MessageWasReadAtChangedEvent.ts
packages/runtime/src/events/transport/index.ts
packages/runtime/test/transport/messages.test.ts
packages/transport/package.json
packages/transport/src/events/MessageWasReadAtChangedEvent.ts
packages/transport/src/events/index.ts
packages/transport/src/modules/messages/MessageController.ts

Needed in the app to react on these changes.

Feature/add MessageWasReadAtChanged event

---

packages/consumption/src/modules/attributes/AttributesController.ts
packages/consumption/src/modules/attributes/index.ts
packages/consumption/src/modules/attributes/local/LocalAttribute.ts
packages/consumption/src/modules/attributes/local/LocalAttributeDeletionInfo.ts
packages/runtime/src/dataViews/consumption/LocalAttributeDVO.ts
packages/runtime/src/types/consumption/LocalAttributeDTO.ts
packages/runtime/src/useCases/consumption/attributes/AttributeMapper.ts

I separated this from #36 , since it is also required for other use cases regarding Attribute deletion, that are otherwise independent of the deletion of peer shared Attributes. Merging this already would allow me to publish further PRs.

Feature/Add deletionInfo to LocalAttribute

---

packages/consumption/src/modules/attributes/AttributesController.ts
packages/consumption/test/modules/attributes/AttributesController.test.ts

I'll be needing the method getPredecessorsOfAttribute to implement the deletion of all predecessors when deleting an Attribute as discussed.

Feature/Add methods to get all predecessors and successors of an Attribute

---

packages/consumption/src/consumption/CoreErrors.ts
packages/consumption/src/modules/attributes/local/LocalAttribute.ts
packages/consumption/src/modules/requests/itemProcessors/freeText/FreeTextRequestItemProcessor.ts
packages/consumption/src/modules/requests/itemProcessors/proposeAttribute/ProposeAttributeRequestItemProcessor.ts
packages/consumption/src/modules/requests/itemProcessors/readAttribute/ReadAttributeRequestItemProcessor.ts
packages/consumption/test/modules/requests/itemProcessors/proposeAttribute/ProposeAttributeRequestItemProcessor.test.ts
packages/consumption/test/modules/requests/itemProcessors/readAttribute/ReadAttributeRequestItemProcessor.test.ts
packages/runtime/src/dataViews/DataViewExpander.ts
packages/runtime/src/useCases/common/Schemas.ts
packages/runtime/test/dataViews/requestItems/ProposeAttributeRequestItemDVO.test.ts
packages/runtime/test/dataViews/requestItems/ReadAttributeRequestItemDVO.test.ts

Basically, what has already been implemented for the ReadAttributeRequestItemProcessor.

Feature/AttributeSuccessionAcceptResponseItem for ProposeAttributeRequestItemProcessor

---

packages/iql/demo/attributes.js

This PR removes any fakes from the IQL demo and replaces them with existing attribute values. This data will subsequently be used for our documentation, too. So if you feel that more (or less) examples are needed do let me know.

Chore/Use real attribute values for IQL demo

---

packages/consumption/test/modules/attributes/AttributesController.test.ts

These are the tests I added in #185 that actually are independent of default Attribute. I didn't bump the version, since I only add tests here.

Test/Full Attribute deletion process

---

packages/consumption/src/modules/requests/itemProcessors/shareAttribute/ShareAttributeRequestItemProcessor.ts
packages/consumption/test/modules/requests/itemProcessors/shareAttribute/ShareAttributeRequestItemProcessor.test.ts
packages/runtime/test/consumption/attributes.test.ts

This tackles the open comments from @britsta on https://github.com/nmshd/runtime/pull/174

Fix/ShareAttribute with deletionInfo

---

packages/consumption/src/consumption/ConsumptionControllerName.ts

Remove unused ConsumptionControllerNames

---

packages/app-runtime/src/AppRuntime.ts

Update feature introduced in #238 to be actually usable.

DatabaseFolder config from nativeEnvironment is ignored

---

.ci/writeBuildInformation.sh
.github/workflows/publish.yml

Package versions does not land in the buildInformation

---

.github/workflows/test.yml

We want our pipelines to be fast. Making our slowest pipelines even slower by adding the codecov uploads to them was not a good idea - so I moved them.

Move codecov to the fastest tests

---

packages/runtime/src/modules/DeciderModule.ts
packages/runtime/test/modules/DeciderModule.test.ts

This PR contains some refactorings I came across working on automating Request that should not clutter the actual PR.

Simplify Decider module

---

package-lock.json
packages/runtime/src/Runtime.ts
packages/runtime/src/useCases/common/AbstractCorrelator.ts
packages/runtime/src/useCases/common/UseCase.ts
packages/runtime/src/useCases/index.ts
packages/runtime/test/lib/RuntimeServiceProvider.ts
packages/runtime/test/lib/TestRuntime.ts
packages/runtime/test/misc/CorrelationId.test.ts
packages/transport/package.json
packages/transport/src/core/ICorrelator.ts
packages/transport/src/core/Transport.ts
packages/transport/src/core/backbone/Authenticator.ts
packages/transport/src/core/backbone/RESTClient.ts
packages/transport/src/core/backbone/RESTClientAuthenticate.ts
packages/transport/src/core/index.ts
packages/transport/src/modules/accounts/AccountController.ts
packages/transport/src/modules/accounts/IdentityDeletionProcessController.ts
packages/transport/src/modules/backboneCompatibility/BackboneCompatibilityController.ts
packages/transport/src/modules/challenges/ChallengeController.ts
packages/transport/src/modules/devices/DevicesController.ts
packages/transport/src/modules/files/FileController.ts
packages/transport/src/modules/messages/MessageController.ts
packages/transport/src/modules/relationshipTemplates/RelationshipTemplateController.ts
packages/transport/src/modules/relationships/RelationshipsController.ts
packages/transport/src/modules/sync/SyncController.ts
packages/transport/src/modules/sync/backbone/SyncClient.ts
packages/transport/src/modules/tokens/AnonymousTokenController.ts
packages/transport/src/modules/tokens/TokenController.ts
packages/transport/test/core/backbone/CorrelationId.test.ts
packages/transport/test/testHelpers/TestUtil.ts

Hopefully better version of #275 without having to remove the feature completely.

Use `correlation-id` package only for testing

---

packages/runtime/test/transport/identityDeletionPeerProcessing.test.ts

-   [X] I added/updated tests.
-   [ ] I ensured that the PR title is good enough for the changelog.

Unstable tests

---

package-lock.json
package.json
packages/runtime/src/dataViews/DataViewExpander.ts
packages/runtime/src/dataViews/transport/RelationshipDVO.ts
packages/runtime/src/types/transport/RelationshipDTO.ts
packages/runtime/test/transport/identityDeletionPeerProcessing.test.ts
packages/transport/src/modules/relationships/local/PeerDeletionInfo.ts
packages/transport/src/modules/sync/externalEventProcessors/PeerDeletedExternalEventProcessor.ts
packages/transport/src/modules/sync/externalEventProcessors/PeerToBeDeletedExternalEventProcessor.ts
packages/transport/test/modules/relationships/PeerDeletionInfo.test.ts
packages/transport/test/modules/sync/externalEventProcessors/PeerDeletedExternalEventProcessor.test.ts
packages/transport/test/modules/sync/externalEventProcessors/PeerToBeDeletedExternalEventProcessor.test.ts

Add `deletionDate` to relationship's deletion info

---

package-lock.json
package.json
packages/consumption/src/modules/requests/itemProcessors/utility/validateAttributeMatchesWithQuery.ts
packages/transport/package.json
packages/transport/src/core/CoreCrypto.ts
packages/transport/src/core/Reference.ts
packages/transport/src/core/TransportCoreErrors.ts
packages/transport/src/core/backbone/RESTClient.ts
packages/transport/src/modules/accounts/IdentityDeletionProcessController.ts
packages/transport/src/modules/sync/DatawalletModificationsProcessor.ts
packages/transport/src/modules/tokens/TokenController.ts
packages/transport/test/core/backbone/Paginator.test.ts
packages/transport/test/modules/PublicAPI.test.ts
packages/transport/test/modules/relationships/RelationshipsController.test.ts
packages/transport/test/testHelpers/FakeSyncClient.ts
packages/transport/test/utils/Random.test.ts
packages/transport/test/utils/Reflection.test.ts

As described in https://github.com/form-data/form-data/issues/563 we want to make sure to be ready for node 23. As `form-data` 4.0.1 is now released this should do the job.

Upgrade the `form-data` lib

---

packages/app-runtime/test/lib/TestUtil.ts
packages/consumption/test/core/TestUtil.ts
packages/runtime/test/lib/RuntimeServiceProvider.ts
packages/transport/test/testHelpers/TestUtil.ts

Make addressGenerationHostnameOverride configurable for tests

---

packages/runtime/src/useCases/common/Schemas.ts

-   [ ] I ensured that the PR title is good enough for the changelog.

Build schemas

---

.github/workflows/publish.yml
.github/workflows/test.yml

Publishing is completely broken [under Node.js 23](https://github.com/nodejs/node/issues/55410). Linked issue is closed, but fix not yet published.

Downgrade Node.js

---

packages/runtime/test/consumption/identityMetadata.test.ts

errorMessage and code are treated as regexes which makes this test be sucessful with two empty strings.

Refine IdentityMetadata tests

---

.ci/checkGitDiff.sh
.github/workflows/check-schema.yml
packages/runtime/src/useCases/transport/devices/GetDevice.ts

Add checks as pipeline run for PRs, that PRs like #324 never come up again.
The new pipeline
1. builds the libs
2. builds the schemas
3. if there is a diff

Check runtime schemas

---

packages/consumption/test/modules/attributeListeners/AttributeListenersController.test.ts
packages/consumption/test/modules/attributes/AttributesController.test.ts
packages/consumption/test/modules/requests/itemProcessors/proposeAttribute/ProposeAttributeRequestItemProcessor.test.ts
packages/consumption/test/modules/requests/itemProcessors/readAttribute/ReadAttributeRequestItemProcessor.test.ts
packages/consumption/test/modules/requests/itemProcessors/registerAttributeListener/RegisterAttributeListenerRequestItemProcessor.test.ts
packages/consumption/test/modules/requests/itemProcessors/shareAttribute/ShareAttributeRequestItemProcessor.test.ts
packages/consumption/test/modules/requests/itemProcessors/utility/validateAttributeMatchesWithQuery.test.ts
packages/consumption/test/modules/requests/testHelpers/TestObjectFactory.ts
packages/content/test/attributes/IQLQuery.test.ts
packages/content/test/attributes/RelationshipAttribute.test.ts
packages/content/test/requests/items/ProposeAttributeRequestItem.test.ts
packages/runtime/test/consumption/attributes.test.ts
packages/runtime/test/consumption/iqlQuery.test.ts
packages/runtime/test/dataViews/MessageDVO.test.ts
packages/runtime/test/dataViews/RelationshipDVO.test.ts
packages/runtime/test/dataViews/RelationshipTemplateDVO.test.ts
packages/runtime/test/lib/testUtils.ts
packages/runtime/test/modules/AttributeListenerModule.test.ts
packages/runtime/test/modules/RequestModule.test.ts
packages/runtime/test/transport/tokens.test.ts

Refine test payloads

---

packages/runtime/test/modules/RequestModule.test.ts

Fix flaky test

---

packages/runtime/src/types/transport/RelationshipDTO.ts
packages/runtime/src/useCases/transport/relationships/RelationshipMapper.ts
packages/transport/src/modules/relationships/local/RelationshipAuditLog.ts
packages/transport/src/modules/relationships/local/RelationshipAuditLogEntry.ts
packages/transport/src/modules/relationships/transmission/RelationshipAuditLog.ts

Support Relationship Decomposition Based Identity Deletion

---

.github/PULL_REQUEST_TEMPLATE.md

Extend PR readiness checklist by self-review checkbox

---

packages/consumption/src/consumption/ConsumptionCoreErrors.ts
packages/consumption/src/modules/attributes/AttributesController.ts
packages/consumption/test/modules/attributes/AttributesController.test.ts
packages/consumption/test/modules/requests/itemProcessors/proposeAttribute/ProposeAttributeRequestItemProcessor.test.ts
packages/consumption/test/modules/requests/itemProcessors/readAttribute/ReadAttributeRequestItemProcessor.test.ts
packages/consumption/test/modules/requests/testHelpers/TestObjectFactory.ts

Attributes can be succeeded without changing their content

---

packages/consumption/src/modules/attributes/AttributesController.ts

-   [X] I ensured that the PR title is good enough for the changelog.
-   [X] I self-reviewed the PR.

Don't compare classes with `_.isEqual`

---

.github/settings.yaml

Should change nothing in this repository, but makes it easy to sync our repositories. Visit https://probot.github.io/apps/settings/ to read more about how this file works.

Configure GitHub repo using settings file

---

packages/runtime/test/transport/messages.test.ts

Flaky queued Notifications test

---

.github/release.yml

Update release config

---

packages/transport/test/testHelpers/TestUtil.ts

Backbone Pipelines are not running for a while, see https://github.com/nmshd/backbone/actions/runs/12273313738/job/34244076275?pr=970.
This makes the idp job runner configurable for testing against every backbone.

Make identity deletion job configurable

---

packages/core-types/src/CoreDate.ts
packages/core-types/test/CoreDate.test.ts

DateTime from DateTime does not return the same date

---

packages/runtime/src/dataViews/consumption/PeerRelationshipTemplateDVO.ts
packages/runtime/src/dataViews/transport/RelationshipTemplateDVO.ts
packages/runtime/src/types/transport/PasswordProtectionDTO.ts
packages/runtime/src/types/transport/RelationshipTemplateDTO.ts
packages/runtime/src/types/transport/TokenDTO.ts
packages/runtime/src/types/transport/index.ts

Add PasswordProtectionDTO

---

.github/workflows/test.yml

Remove FerretDB pipelines

---

packages/runtime/src/modules/DeciderModule.ts
packages/runtime/src/modules/decide/RequestConfig.ts
packages/runtime/test/modules/DeciderModule.test.ts

Extend RequestConfig of DeciderModule depending on existence of Relationship

---

packages/runtime/src/events/transport/DatawalletSynchronizedEvent.ts
packages/transport/src/events/DatawalletSynchronizedEvent.ts
packages/transport/src/modules/sync/SyncController.ts

Do not emit DatawalletSynchronizedEvent with disabled Datawallet

---

packages/consumption/test/modules/attributes/AttributesController.test.ts
packages/content/src/attributes/types/identity/SchematizedXML.ts
packages/content/src/attributes/types/proprietary/ProprietaryXML.ts

 `schemaURL` of XML Attributes is not nullable

---

.dev/compose.yml
packages/consumption/package.json
packages/runtime/package.json
packages/transport/package.json

Update FerretDB to V2 (see https://docs.ferretdb.io/installation/ferretdb/docker/ for v2 docs) for local testing.
CI is still out of scope here.

FerretDB v2 local testing setup

---

packages/content/src/attributes/hints/ValueHints.ts

Don't use serval's `unionTypes` with primitive types

---

.dev/compose.backbone.yml
packages/app-runtime/test/modules/SSEModule.test.ts

Upgrade RabbitMQ for local backbone

---

packages/app-runtime/src/modules/appEvents/RelationshipTemplateProcessedModule.ts

Rename handleRelationshipTemplateProcessed method

---

packages/runtime/src/dataViews/transport/FileDVO.ts
packages/runtime/src/types/transport/FileDTO.ts
packages/runtime/src/useCases/common/Schemas.ts
packages/runtime/src/useCases/transport/files/FileMapper.ts
packages/runtime/src/useCases/transport/files/GetFiles.ts
packages/runtime/src/useCases/transport/files/UploadOwnFile.ts
packages/runtime/test/transport/files.test.ts
packages/transport/src/modules/files/FileController.ts
packages/transport/src/modules/files/local/CachedFile.ts
packages/transport/src/modules/files/local/SendFileParameters.ts
packages/transport/src/modules/files/transmission/FileMetadata.ts
packages/transport/test/modules/files/FileController.test.ts
packages/transport/test/testHelpers/TestUtil.ts

Enrich metadata of File with tags

---

packages/consumption/src/modules/common/index.ts
packages/consumption/src/modules/common/mergeResults.ts
packages/consumption/src/modules/requests/incoming/DecideRequestParametersValidator.ts
packages/consumption/src/modules/requests/incoming/IncomingRequestsController.ts
packages/consumption/test/modules/requests/DecideRequestParametersValidator.test.ts
packages/consumption/test/modules/requests/IncomingRequestsController.test.ts

Return all CanDecide errors simultaneously

---

packages/runtime/test/consumption/attributes.test.ts
packages/runtime/test/dataViews/SharedToPeerAttributeDVO.test.ts
packages/runtime/test/dataViews/requestItems/ComplexReadAttributeRequestItemDVO.test.ts
packages/runtime/test/dataViews/requestItems/CreateIdentityAttributeRequestItemDVO.test.ts
packages/runtime/test/dataViews/requestItems/DeleteAttributeRequestItemDVO.test.ts
packages/runtime/test/dataViews/requestItems/ReadAttributeRequestItemDVO.test.ts
packages/runtime/test/lib/testUtils.ts
packages/runtime/test/transport/relationships.test.ts

... and refactor some stuff to keep #423 clean.

Extent testUtil to delete all shared Attributes

---

.dev/compose.backbone.yml
packages/app-runtime/test/modules/appEvents/RelationshipTemplateProcessedModule.test.ts
packages/runtime/test/modules/RequestModule.test.ts

Add more tests for RelationshipTemplateProcessedResult.RequestExpired

---

packages/consumption/src/consumption/ConsumptionCoreErrors.ts
packages/consumption/src/modules/requests/incoming/IncomingRequestsController.ts
packages/consumption/test/modules/requests/DeleteRequest.test.ts
packages/runtime/src/extensibility/facades/consumption/IncomingRequestsFacade.ts
packages/runtime/src/useCases/common/Schemas.ts
packages/runtime/src/useCases/consumption/requests/DeleteIncomingRequest.ts
packages/runtime/src/useCases/consumption/requests/index.ts
packages/runtime/test/consumption/requests.test.ts

Delete incoming requests

---

packages/consumption/src/modules/requests/itemProcessors/createAttribute/CreateAttributeRequestItemProcessor.ts
packages/consumption/test/modules/requests/itemProcessors/readAttribute/ReadAttributeRequestItemProcessor.test.ts

The diff of the test gives the impression that this is more of a change than it actually is. 😆

Fix typo and clean up ReadAttributeRequestItemProcessor test

---

packages/consumption/src/modules/requests/itemProcessors/readAttribute/ReadAttributeRequestItemProcessor.ts

... as preparation for more changes in the ReadAttributeRequestItemProcessor

Refactor ReadAttributeRequestItemProcessor

---

packages/app-runtime/src/modules/AppSyncModule.ts
packages/app-runtime/src/modules/PushNotificationModule.ts
packages/app-runtime/src/modules/SSEModule.ts
packages/app-runtime/src/modules/appEvents/MailReceivedModule.ts
packages/app-runtime/src/modules/appEvents/OnboardingChangeReceivedModule.ts
packages/app-runtime/src/modules/appEvents/RelationshipTemplateProcessedModule.ts
packages/app-runtime/src/modules/runtimeEvents/IdentityDeletionProcessStatusChangedModule.ts
packages/app-runtime/src/modules/runtimeEvents/MessageReceivedModule.ts
packages/app-runtime/src/modules/runtimeEvents/RelationshipChangedModule.ts
packages/app-runtime/test/runtime/RuntimeModuleLoadingTest.test.ts
packages/runtime/src/extensibility/modules/RuntimeModule.ts
packages/runtime/src/modules/AttributeListenerModule.ts
packages/runtime/src/modules/DeciderModule.ts
packages/runtime/src/modules/MessageModule.ts
packages/runtime/src/modules/NotificationModule.ts
packages/runtime/src/modules/RequestModule.ts

As it's not possible in js/ts to make sure that the super method is called in an override I used the method provided in https://stackoverflow.com/a/75250861/10029378 to make sure unsubscribeFromAllEvents is called for every module. This is a preparation for writing the documentation about custom modules.

`unsubscribeFromAllEvents` is not safe to be called in every module

---

packages/consumption/test/modules/attributes/AttributesController.test.ts
packages/consumption/test/modules/requests/itemProcessors/createAttribute/CreateAttributeRequestItemProcessor.test.ts
packages/runtime/test/consumption/attributes.test.ts

After pull requests were merged into the branch release/v7, tests failed because the pull requests interfered with each other. The failure of the tests is fixed in this PR.

Failing tests after merged pull requests

---

packages/app-runtime/test/modules/MessageEventing.test.ts
packages/consumption/test/modules/attributes/AttributesController.test.ts
packages/consumption/test/modules/requests/itemProcessors/readAttribute/ReadAttributeRequestItemProcessor.test.ts
packages/content/test/attributeValues/AddressValueTests.test.ts
packages/content/test/attributes/EMailAddress.test.ts
packages/content/test/messages/Mail.test.ts
packages/runtime/test/consumption/attributes.test.ts
packages/runtime/test/dataViews/DraftIdentityAttributeDVO.test.ts
packages/runtime/test/dataViews/IQLQueryExpanded.test.ts
packages/runtime/test/dataViews/MessageDVO.test.ts
packages/runtime/test/dataViews/RepositoryAttributeDVO.test.ts
packages/runtime/test/lib/testUtils.ts
packages/runtime/test/transport/messages.test.ts
packages/runtime/test/transport/relationships.test.ts
packages/transport/test/end2end/End2End.test.ts
packages/transport/test/modules/certificates/CertificateIssuer.test.ts
packages/transport/test/modules/messages/MessageContent.test.ts

Use standardized test values

---

.github/dependabot.yml

Reduce dependabot npm updates reviewers

---

packages/consumption/test/core/TestUtil.ts
packages/runtime/test/lib/testUtils.ts
packages/transport/test/modules/sync/SyncController.files.test.ts

Use descriptive File properties

---

packages/consumption/test/modules/requests/itemProcessors/proposeAttribute/ProposeAttributeRequestItemProcessor.test.ts
packages/consumption/test/modules/requests/itemProcessors/readAttribute/ReadAttributeRequestItemProcessor.test.ts

The tests are only refactored and not changed. Serves as preparation for adding new tests.

Refactor ProposeAttributeRequestItemProcessor tests

---

packages/consumption/src/modules/requests/itemProcessors/proposeAttribute/AcceptProposeAttributeRequestItemParameters.ts
packages/consumption/src/modules/requests/itemProcessors/proposeAttribute/ProposeAttributeRequestItemProcessor.ts
packages/consumption/src/modules/requests/itemProcessors/utility/createAppropriateResponseItem.ts
packages/consumption/test/modules/requests/itemProcessors/proposeAttribute/ProposeAttributeRequestItemProcessor.test.ts

Prevent creation of RepositoryAttribute duplicates by accepting a ProposeAttributeRequestItem

---

packages/consumption/test/modules/requests/itemProcessors/shareAttribute/ShareAttributeRequestItemProcessor.test.ts

Refactor ShareAttributeRequestItemProcessor test

---

packages/consumption/test/modules/requests/itemProcessors/proposeAttribute/ProposeAttributeRequestItemProcessor.test.ts
packages/consumption/test/modules/requests/itemProcessors/readAttribute/ReadAttributeRequestItemProcessor.test.ts
packages/transport/test/modules/sync/SyncController.relationships.test.ts

Test failures

---

packages/runtime/src/dataViews/DataViewExpander.ts
packages/runtime/src/dataViews/transport/RelationshipDVO.ts
packages/runtime/test/dataViews/RelationshipDVO.test.ts
packages/runtime/test/lib/testUtils.ts

Add sendMailDisabled to RelationshipDVO

---

packages/runtime/src/useCases/common/RuntimeErrors.ts
packages/runtime/test/transport/relationshipTemplates.test.ts

Remove more QR code wordings

---

packages/consumption/test/modules/requests/itemProcessors/formField/FormFieldRequestItemProcessor.test.ts

Refactorings from #491 that do not belong there.

Update test naming

---

packages/runtime/test/modules/DeciderModule.test.ts

Automatically decide AuthenticationRequestItem with configured `title`

---

packages/content/src/attributes/types/relationship/Consent.ts
packages/runtime/src/useCases/common/Schemas.ts

Missing type annotation in `ConsentJSON`

---

packages/transport/src/core/TransportCoreErrors.ts

Delete unused error

---

packages/runtime/test/transport/passwordProtection/deviceOnboardingToken.test.ts
packages/runtime/test/transport/passwordProtection/files.test.ts
packages/runtime/test/transport/passwordProtection/relationshipTemplates.test.ts
packages/runtime/test/transport/passwordProtection/tokens.test.ts

Check validation error message explicitly

---

packages/runtime/src/useCases/common/validation/TokenAndTemplateCreationValidator.ts
packages/runtime/test/common/TokenAndTemplateCreationValidator.test.ts
packages/runtime/test/transport/passwordProtection/deviceOnboardingToken.test.ts
packages/runtime/test/transport/passwordProtection/files.test.ts
packages/runtime/test/transport/passwordProtection/relationshipTemplates.test.ts
packages/runtime/test/transport/passwordProtection/tokens.test.ts

It is possible to set `0` as PasswordLocationIndicator

---

packages/app-runtime/src/modules/SSEModule.ts
packages/consumption/src/modules/requests/itemProcessors/createAttribute/CreateAttributeRequestItemProcessor.ts
packages/consumption/src/modules/requests/itemProcessors/proposeAttribute/ProposeAttributeRequestItemProcessor.ts
packages/consumption/src/modules/requests/itemProcessors/readAttribute/ReadAttributeRequestItemProcessor.ts
packages/consumption/src/modules/requests/itemProcessors/shareAttribute/ShareAttributeRequestItemProcessor.ts
packages/consumption/src/modules/requests/itemProcessors/transferFileOwnership/TransferFileOwnershipRequestItemProcessor.ts
packages/consumption/src/modules/requests/itemProcessors/utility/validateAttributeMatchesWithQuery.ts
packages/content/src/attributes/types/relationship/Consent.ts
packages/content/src/requests/items/consent/ConsentRequestItem.ts
packages/content/src/requests/items/proposeAttribute/ProposeAttributeRequestItem.ts
packages/runtime/src/modules/DeciderModule.ts
packages/runtime/src/useCases/common/PasswordProtectionMapper.ts

Unify undefined checks

---

packages/consumption/src/modules/attributes/AttributesController.ts
packages/runtime/src/useCases/consumption/attributes/CanCreateRepositoryAttribute.ts
packages/runtime/test/consumption/attributes.test.ts

Validate tags in CanCreateRepositoryAttribute

---

packages/runtime/test/consumption/attributes.test.ts

Test validation of successor

---

.github/renovate.json5

Add renovate rangeStrategy

---

packages/runtime/src/useCases/transport/account/SyncEverything.ts

Remove unused logger from SyncEverything

---

packages/runtime/src/modules/RequestModule.ts
packages/runtime/test/transport/relationships.test.ts

Rename variable and make tests less dependent

---

packages/consumption/src/modules/requests/itemProcessors/transferFileOwnership/TransferFileOwnershipRequestItemProcessor.ts
packages/consumption/test/core/TestUtil.ts
packages/consumption/test/modules/requests/RequestEnd2End.test.ts
packages/consumption/test/modules/requests/itemProcessors/transferFileOwnership/TransferFileOwnershipRequestItemProcessor.test.ts
packages/content/src/attributes/types/strings/AbstractFileReference.ts
packages/runtime/src/ConfigHolder.ts
packages/runtime/src/Runtime.ts
packages/runtime/src/useCases/transport/files/FileMapper.ts
packages/runtime/src/useCases/transport/relationshipTemplates/RelationshipTemplateMapper.ts
packages/runtime/src/useCases/transport/tokens/TokenMapper.ts
packages/transport/src/modules/files/local/File.ts
packages/transport/src/modules/messages/MessageController.ts
packages/transport/src/modules/relationshipTemplates/local/RelationshipTemplate.ts
packages/transport/src/modules/tokens/local/Token.ts
packages/transport/test/end2end/End2End.test.ts
packages/transport/test/modules/files/FileController.test.ts
packages/transport/test/modules/relationshipTemplates/RelationshipTemplateController.test.ts
packages/transport/test/modules/relationships/decomposition.test.ts
packages/transport/test/modules/sync/SyncController.relationships.test.ts
packages/transport/test/modules/tokens/AnonymousTokenController.test.ts
packages/transport/test/modules/tokens/TokenController.test.ts
packages/transport/test/testHelpers/TestUtil.ts

Add the backboneBaseUrl to all truncated references

---

packages/app-runtime/test/lib/TestUtil.ts
packages/app-runtime/test/modules/appEvents/RelationshipTemplateProcessedModule.test.ts
packages/app-runtime/test/runtime/AppStringProcessor.test.ts
packages/app-runtime/test/runtime/Onboarding.test.ts
packages/runtime/src/dataViews/DataViewExpander.ts
packages/runtime/src/types/transport/FileDTO.ts
packages/runtime/src/types/transport/RelationshipTemplateDTO.ts
packages/runtime/src/types/transport/TokenDTO.ts
packages/runtime/src/useCases/transport/files/FileMapper.ts
packages/runtime/src/useCases/transport/relationshipTemplates/RelationshipTemplateMapper.ts
packages/runtime/src/useCases/transport/tokens/TokenMapper.ts
packages/runtime/test/anonymous/tokens.test.ts
packages/runtime/test/dataViews/IdentityDVO.test.ts
packages/runtime/test/dataViews/RelationshipTemplateDVO.test.ts
packages/runtime/test/dataViews/requestItems/TransferFileOwnershipRequestItemDVO.test.ts
packages/runtime/test/lib/testUtils.ts
packages/runtime/test/modules/DeciderModule.test.ts
packages/runtime/test/modules/RequestModule.test.ts
packages/runtime/test/transport/account.test.ts
packages/runtime/test/transport/files.test.ts
packages/runtime/test/transport/passwordProtection/deviceOnboardingToken.test.ts
packages/runtime/test/transport/passwordProtection/files.test.ts
packages/runtime/test/transport/passwordProtection/relationshipTemplates.test.ts
packages/runtime/test/transport/passwordProtection/tokens.test.ts
packages/runtime/test/transport/relationshipTemplates.test.ts
packages/runtime/test/transport/tokens.test.ts

Remove truncatedReference from DTOs

---

packages/app-runtime/src/AppRuntimeErrors.ts
packages/app-runtime/src/AppStringProcessor.ts
packages/app-runtime/test/runtime/AppStringProcessor.test.ts

The AppStringProcessor error codes are not consistent

---

packages/consumption/test/modules/requests/IncomingRequestsController.test.ts
packages/consumption/test/modules/requests/itemProcessors/readAttribute/ReadAttributeRequestItemProcessor.test.ts

Test validation accepting a ReadAttributeRequestItem with a new Attribute

---

packages/consumption/test/modules/attributes/AttributesController.test.ts

Change location of test

---

packages/consumption/src/modules/attributes/AttributesController.ts
packages/consumption/test/modules/attributes/AttributesController.test.ts
packages/consumption/test/modules/requests/itemProcessors/createAttribute/Context.ts
packages/consumption/test/modules/requests/itemProcessors/createAttribute/CreateAttributeRequestItemProcessor.test.ts
packages/consumption/test/modules/requests/itemProcessors/proposeAttribute/ProposeAttributeRequestItemProcessor.test.ts
packages/consumption/test/modules/requests/itemProcessors/readAttribute/ReadAttributeRequestItemProcessor.test.ts
packages/consumption/test/modules/requests/itemProcessors/shareAttribute/ShareAttributeRequestItemProcessor.test.ts
packages/consumption/test/modules/requests/itemProcessors/transferFileOwnership/TransferFileOwnershipRequestItemProcessor.test.ts
packages/consumption/test/modules/requests/itemProcessors/utility/validateAttributeMatchesWithQuery.test.ts
packages/content/test/attributes/IQLQuery.test.ts
packages/content/test/attributes/IdentityAttributeQuery.test.ts
packages/runtime/test/consumption/attributes.test.ts
packages/runtime/test/consumption/iqlQuery.test.ts
packages/runtime/test/dataViews/IQLQueryExpanded.test.ts
packages/runtime/test/dataViews/IdentityAttributeQueryExpanded.test.ts
packages/runtime/test/dataViews/requestItems/ProposeAttributeRequestItemDVO.test.ts
packages/runtime/test/dataViews/requestItems/ReadAttributeRequestItemDVO.test.ts
packages/runtime/test/modules/DeciderModule.test.ts
packages/runtime/test/transport/files.test.ts

Make tag validation less breaking

---

packages/app-runtime/src/AppStringProcessor.ts
packages/app-runtime/test/runtime/AppStringProcessor.test.ts
packages/core-types/src/references/Reference.ts
packages/core-types/test/references/Reference.test.ts

Do not process nmshd links anymore

---

packages/content/src/requests/response/AcceptResponseItem.ts
packages/runtime/src/useCases/common/Schemas.ts

Add TransferFileOwnershipAcceptResponseItem to AcceptResponseItemDerivation

---

packages/runtime/src/events/EventProxy.ts
packages/runtime/src/events/transport/RelationshipTemplateAllocationsExhaustedEvent.ts
packages/runtime/src/events/transport/index.ts
packages/transport/src/events/RelationshipTemplateAllocationsExhaustedEvent.ts
packages/transport/src/events/index.ts
packages/transport/src/modules/sync/externalEventProcessors/ExternalEventProcessorRegistry.ts
packages/transport/src/modules/sync/externalEventProcessors/RelationshipTemplateAllocationsExhaustedProcessor.ts

This is a new external event in the backbone and was spamming the logs for a while.

Handle the RelationshipTemplateAllocationsExhaustedExternalEvent

---

packages/runtime/src/dataViews/DataViewExpander.ts

Keep https://github.com/nmshd/runtime/pull/545 clean.

Adjust formatting and variable names in DataViewExpander

---

packages/app-runtime/src/AppStringProcessor.ts

Cancelling the password prompt shows an error in the app

---

packages/runtime/src/useCases/common/Schemas.ts
packages/runtime/src/useCases/transport/tokens/GetTokens.ts

Add property `isOwn` of the Token to the use case for querying Tokens.

Add `isOwn` property to GetTokens use case

---

packages/app-runtime/src/AppRuntimeErrors.ts
packages/app-runtime/src/AppStringProcessor.ts
packages/app-runtime/test/runtime/AppStringProcessor.test.ts

Add processDeviceOnboardingReference to AppStringProcessor

---

packages/app-runtime/src/AppStringProcessor.ts

Accounts in deletion are proposed in requestAccountSelection

---

packages/runtime/src/modules/DeciderModule.ts

Refactor DeciderModule

---

packages/consumption/src/modules/requests/incoming/IncomingRequestsController.ts
packages/consumption/src/modules/requests/outgoing/OutgoingRequestsController.ts
packages/runtime/test/consumption/requests.test.ts

RequestStatusChanged events are not published for expired requests

---

package-lock.json
packages/consumption/test/modules/requests/itemProcessors/transferFileOwnership/TransferFileOwnershipRequestItemProcessor.test.ts

Move File uploads into tests

---

.dev/compose.backbone.yml
packages/runtime/src/events/EventProxy.ts
packages/runtime/src/events/transport/FileOwnershipClaimedEvent.ts
packages/runtime/src/events/transport/index.ts
packages/transport/src/events/FileOwnershipClaimedEvent.ts
packages/transport/src/events/index.ts
packages/transport/src/modules/files/local/File.ts
packages/transport/src/modules/sync/externalEventProcessors/ExternalEventProcessorRegistry.ts
packages/transport/src/modules/sync/externalEventProcessors/FileOwnershipClaimedExternalEventProcessor.ts
packages/transport/src/modules/sync/externalEventProcessors/FileOwnershipLockedExternalEventProcessor.ts
packages/transport/test/modules/files/FileController.test.ts

Handle FileOwnershipClaimed external event

---

.ci/runChecks.sh
package-lock.json

Audit exclude

---

packages/transport/src/events/MessageDeliveredEvent.ts
packages/transport/src/events/MessageReceivedEvent.ts
packages/transport/src/events/MessageSentEvent.ts
packages/transport/src/events/MessageWasReadAtChangedEvent.ts
packages/transport/src/events/PeerRelationshipTemplateLoadedEvent.ts
packages/transport/src/events/RelationshipChangedEvent.ts
packages/transport/src/events/RelationshipReactivationCompletedEvent.ts
packages/transport/src/events/RelationshipReactivationRequestedEvent.ts
packages/transport/src/events/RelationshipTemplateAllocationsExhaustedEvent.ts

Use barrel imports

---

packages/consumption/test/modules/requests/IncomingRequestsController.test.ts
packages/consumption/test/modules/requests/RequestsIntegrationTest.ts

Refactoring in separate PR to keep https://github.com/nmshd/runtime/pull/612 clean.

Simplify tests for creating incoming Request

---

packages/runtime-types/package.json

There is no test folder to lint.

Update lint script

---

packages/app-runtime/test/lib/TestUtil.ts
packages/consumption/test/core/TestUtil.ts
packages/content/src/messages/Mail.ts
packages/core-types/src/CoreDate.ts
packages/runtime/src/DatabaseSchemaUpgrader.ts
packages/runtime/src/useCases/transport/messages/GetMessages.ts
packages/runtime/test/lib/QueryParamConditions.ts
packages/transport/src/core/backbone/RESTClient.ts
packages/transport/src/modules/files/FileController.ts
packages/transport/src/modules/messages/MessageController.ts
packages/transport/src/modules/messages/transmission/MessageContentWrapper.ts
packages/transport/src/modules/relationships/RelationshipsController.ts
packages/transport/src/modules/sync/SyncController.ts
packages/transport/test/modules/messages/MessageContent.test.ts
packages/transport/test/testHelpers/TestUtil.ts

Satisfy linter

---

packages/consumption/test/modules/attributes/AttributesController.test.ts
packages/runtime/test/misc/DatabaseSchemaUpgrader.test.ts
packages/runtime/test/transport/messages.test.ts
packages/runtime/test/transport/relationships.test.ts
packages/transport/src/modules/accounts/AccountController.ts

Multiple objects with same `id` can be created in the database

---

packages/runtime/src/modules/DeciderModule.ts
packages/runtime/test/lib/RuntimeServiceProvider.ts
packages/runtime/test/modules/DeciderModule.test.ts

Get rid of any usage in the decider module

---

packages/runtime/src/modules/DeciderModule.ts
packages/runtime/test/modules/DeciderModule.test.ts

Decider module tests are broken

---

packages/consumption/src/consumption/ConsumptionBaseController.ts
packages/transport/src/core/TransportController.ts
packages/transport/src/modules/tokens/TokenController.ts

Use `fromUnknown` in the `parseArray` method

---

packages/app-runtime/src/AppRuntime.ts
packages/transport/test/modules/sync/BackboneConcurrency.test.ts

Remove todo comments

---

package-lock.json
package.json

Bump npm publish

---

packages/core-types/src/references/Reference.ts
packages/core-types/test/references/Reference.test.ts
packages/runtime/src/useCases/transport/devices/FillDeviceOnboardingTokenWithNewDevice.ts
packages/runtime/test/transport/devices.test.ts
packages/transport/test/modules/files/FileReference.test.ts
packages/transport/test/modules/relationshipTemplates/RelationshipTemplateReference.test.ts
packages/transport/test/modules/tokens/TokenReference.test.ts

The FillDeviceOnboardingTokenWithNewDevice UseCase still does not accept url references

---

packages/runtime/src/extensibility/facades/transport/DevicesFacade.ts
packages/runtime/src/useCases/common/Schemas.ts
packages/runtime/src/useCases/transport/devices/UpdateCurrentDevice.ts
packages/runtime/src/useCases/transport/devices/index.ts
packages/runtime/test/transport/devices.test.ts

Add possibility to update current device

---

packages/runtime/test/consumption/requests.test.ts
packages/runtime/test/lib/testUtilsWithInactiveModules.ts

Update test naming from receiver to recipient

---

packages/app-runtime/test/lib/TestUtil.ts
packages/transport/test/testHelpers/TestUtil.ts

Make network of deletion job configurable
