nmshd/runtime

package-lock.json
packages/content/package.json
packages/content/src/attributes/types/address/AbstractAddress.ts
packages/content/src/attributes/types/address/DeliveryBoxAddress.ts
packages/content/src/attributes/types/address/PostOfficeBoxAddress.ts
packages/content/src/attributes/types/address/StreetAddress.ts
packages/content/src/attributes/types/affiliation/Affiliation.ts
packages/content/src/attributes/types/birth/BirthDate.ts
packages/content/src/attributes/types/birth/BirthPlace.ts
packages/content/src/attributes/types/measurements/AbstractLengthMeasurement.ts
packages/content/src/attributes/types/measurements/AbstractMeasurement.ts
packages/content/src/attributes/types/name/PersonName.ts
packages/content/src/attributes/types/statement/AbstractIdentityDescriptor.ts
packages/content/src/attributes/types/statement/AbstractStatement.ts
packages/content/src/attributes/types/statement/DigitalIdentityDescriptor.ts
packages/content/src/attributes/types/statement/StatementIssuerConditions.ts
packages/content/src/attributes/types/statement/StatementObject.ts
packages/content/src/attributes/types/statement/StatementSubject.ts

easy-tsnameof is outdated and makes problems with the new typescript version: https://github.com/nmshd/runtime/pull/64 this PR can be merged afterwards
no version bumps needed for now, will do them in the bumpy pr #64

Fix/ditch easy-tsnameof

---

packages/consumption/src/modules/attributes/AttributesController.ts
packages/runtime/src/useCases/consumption/attributes/DeleteOwnSharedAttributeAndNotifyPeer.ts
packages/runtime/src/useCases/consumption/attributes/DeletePeerSharedAttributeAndNotifyOwner.ts
packages/runtime/src/useCases/consumption/attributes/DeleteRepositoryAttribute.ts
packages/runtime/test/consumption/attributes.test.ts
packages/runtime/test/lib/testUtils.ts

Deleting a RelationshipAttribute, that is the sourceAttribute of a ThirdPartyRelationshipAttribute, their respective sourceAttribute property will be unset.

Feature/Detach ThirdPartyRelationshipAttributes

---

packages/consumption/src/consumption/ConsumptionController.ts
packages/consumption/src/consumption/CoreErrors.ts
packages/consumption/src/modules/attributes/events/ThirdPartyOwnedRelationshipAttributeDeletedByPeerEvent.ts
packages/consumption/src/modules/attributes/events/index.ts
packages/consumption/src/modules/attributes/local/LocalAttribute.ts
packages/consumption/src/modules/notifications/index.ts
packages/consumption/src/modules/notifications/itemProcessors/attributeDeleted/ThirdPartyOwnedRelationshipAttributeDeletedByPeerNotificationItemProcessor.ts
packages/consumption/test/modules/notifications/itemProcessors/attributeDeleted/ThirdPartyOwnedRelationshipAttributeDeletedByPeerNotificationItemProcessor.test.ts
packages/content/src/notifications/items/ThirdPartyOwnedRelationshipAttributeDeletedByPeerNotificationItem.ts
packages/content/src/notifications/items/index.ts
packages/runtime/src/events/EventProxy.ts
packages/runtime/src/events/consumption/ThirdPartyOwnedRelationshipAttributeDeletedByPeerEvent.ts
packages/runtime/src/events/consumption/index.ts
packages/runtime/src/extensibility/facades/consumption/AttributesFacade.ts
packages/runtime/src/useCases/common/RuntimeErrors.ts
packages/runtime/src/useCases/common/Schemas.ts
packages/runtime/src/useCases/consumption/attributes/DeleteThirdPartyOwnedRelationshipAttributeAndNotifyPeer.ts
packages/runtime/src/useCases/consumption/attributes/index.ts
packages/runtime/test/consumption/attributes.test.ts

The thirdPartyOwned adjustments in the LocalAttribute were copied from #76 .
The ThirdPartyOwnedRelationshipAttributeDeletedByPeerNotificationItemProcessor does the same like the PeerSharedAttributeDeletedByPeerNotificationItemProcessor, but @britsta and I discussed that it still makes sense to have a dedicated ThirdPartyOwnedRelationshipAttributeDeletedByPeerNotificationItem, to be more precise and consistent with the naming (which will also be applied in the documentation), and to be flexible if we want to adjust the handling of the deletion of PeerSharedAttributes compared to ThirdPartyOwnedRelationshipAttributes.

Feature/Delete third party owned RelationshipAttribute use case

---

packages/runtime/test/lib/AdminApiClient.ts
packages/transport/test/testHelpers/AdminApiClient.ts

As the subsequent calls carry the API key, this results in a claims-based user mismatch.
This PR fixes the current behaviour.
Btw, I'm not sure why there are two files, but I fixed both anyway.

Ci/XSRF token being retrieved without the API key makes it invalid for subsequent calls

---

package-lock.json
packages/app-runtime/package.json
packages/app-runtime/src/events/ExternalEventReceivedEvent.ts
packages/app-runtime/src/modules/pushNotifications/PushNotificationModule.ts
packages/runtime/src/useCases/common/Schemas.ts

I used `SyncEverythingResponse` instead of manually adding `identityDeletionProcesses` in order to improve type safety for the future.

Fix/Add identityDeletionProcesses to ExternalEventReceivedEvent

---

package-lock.json
packages/runtime/package.json

Version 2.2.0 would nor build due to error.
https://github.com/vega/ts-json-schema-generator/issues/1967#issuecomment-2131409014
This is already fixed in 2.3.0 prerelease.

fix/pin ts-json-schema-generator version to avoid build errors

---

package-lock.json
packages/consumption/package.json
packages/consumption/src/modules/requests/itemProcessors/proposeAttribute/ProposeAttributeRequestItemProcessor.ts
packages/consumption/src/modules/requests/itemProcessors/readAttribute/ReadAttributeRequestItemProcessor.ts
packages/consumption/test/modules/requests/itemProcessors/proposeAttribute/ProposeAttributeRequestItemProcessor.test.ts
packages/consumption/test/modules/requests/itemProcessors/readAttribute/ReadAttributeRequestItemProcessor.test.ts
packages/runtime/package.json

We discussed this and already allowed this using the ShareAttributeRequestItem (v5). For consistency, this should behave equally using the Read- and ProposeAttributeRequestItem.

Feature/Allow resharing of ToBeDeleted attributes

---

packages/consumption/src/modules/attributes/AttributesController.ts
packages/consumption/test/modules/attributes/AttributesController.test.ts

I previously thought we didn't need this, since when sharing a complex Attribute no child copies are created. However, it is possible to also share child Attributes on their own and then when deleting the complex parent Attribute, these copies need to be detached, too.

Fix/Detach copies of child Attributes

---

packages/app-runtime/src/AppConfig.ts
packages/app-runtime/src/AppRuntime.ts

Update app-runtime config value `dataFolder` to `databaseFolder` to align naming and actual usage

---

.github/workflows/publish.yml

During #236 the environment variable was renamed incorrectly: https://github.com/nmshd/runtime/pull/236/files#diff-551d1fcf87f78cc3bc18a7b332a4dc5d8773a512062df881c5aba28a6f5c48d7. This results in authentication issues during the publish phase.

Properly authentication to npmjs during publish

---

packages/runtime/src/extensibility/facades/consumption/SettingsFacade.ts
packages/runtime/src/useCases/common/Schemas.ts
packages/runtime/src/useCases/consumption/settings/UpsertSettingByKey.ts
packages/runtime/src/useCases/consumption/settings/index.ts
packages/runtime/test/consumption/settings.test.ts

Upsert settings

---

packages/app-runtime/src/multiAccount/MultiAccountController.ts
packages/transport/src/core/TransportCoreErrors.ts
packages/transport/src/modules/accounts/AccountController.ts

Fix/Failing initial sync breaks AccountController

---

packages/consumption/src/modules/requests/itemProcessors/GenericRequestItemProcessor.ts
packages/consumption/test/modules/requests/GenericRequestItemProcessor.test.ts
packages/consumption/test/modules/requests/IncomingRequestsController.test.ts

Apply code and message to RejectResponseItem

---

package-lock.json
packages/runtime/src/useCases/common/UseCase.ts
packages/runtime/test/lib/RequestInterceptor.ts
packages/runtime/test/misc/CorrelationId.test.ts
packages/transport/package.json
packages/transport/src/core/backbone/RESTClient.ts
packages/transport/test/core/backbone/Authentication.test.ts
packages/transport/test/core/backbone/CorrelationId.test.ts

Add correlation ID to all use cases and send it to backbone

---

packages/runtime/test/transport/identityDeletionPeerProcessing.test.ts

Stabilize IdentityDeletionPeerProcessing test

---

packages/consumption/src/consumption/ConsumptionCoreErrors.ts
packages/consumption/src/modules/common/ValidationResult.ts
packages/consumption/src/modules/requests/outgoing/OutgoingRequestsController.ts
packages/consumption/test/modules/requests/DecideRequestParametersValidator.test.ts
packages/consumption/test/modules/requests/IncomingRequestsController.test.ts
packages/consumption/test/modules/requests/OutgoingRequestsController.test.ts
packages/consumption/test/modules/requests/RequestsIntegrationTest.ts
packages/runtime/test/modules/DeciderModule.test.ts

-   [X] I added/updated tests.
-   [X] I ensured that the PR title is good enough for the changelog.

Change the message of "error.consumption.validation.inheritedFromItem" when using canCreate

---

packages/runtime/src/dataViews/DataViewExpander.ts
packages/runtime/src/dataViews/transport/IdentityDVO.ts
packages/runtime/src/dataViews/transport/RelationshipDVO.ts
packages/runtime/src/useCases/common/Schemas.ts
packages/runtime/src/useCases/consumption/settings/GetSettingByKey.ts
packages/runtime/src/useCases/consumption/settings/UpsertSettingByKey.ts
packages/runtime/test/consumption/settings.test.ts
packages/runtime/test/dataViews/RelationshipDVO.test.ts

As the App wants to be able to override names for contacts we have to update the functionality that @stnmtz build with new possibilities from the settings module, to be usable again.
As it is also a requirement to revert the contact name to the runtime default I also return the original name.

Make relationship setting usable

---

packages/runtime/src/dataViews/DataViewExpander.ts

Unsafe `as X` casting destroyed the ShareAttributeRequestItemDVO when the item was rejected.

ShareAttributeRequestItemDVOs `attribute.id` is overridden with with `undefined`

---

packages/app-runtime/test/lib/TestUtil.ts
packages/transport/src/modules/relationships/RelationshipsController.ts

Add support for https://github.com/nmshd/backbone/pull/904.

Remove relationshipRequest naming

---

packages/runtime/src/useCases/common/Schemas.ts
packages/runtime/src/useCases/common/validation/ValidatableStrings.ts
packages/runtime/test/consumption/attributes.test.ts

-   [X] I ensured that the PR title is good enough for the changelog.

Improve address regex

---

packages/consumption/src/modules/attributes/local/LocalAttribute.ts

Feature/Add check for undefined `parentId` of shared Attributes

---

packages/consumption/src/consumption/ConsumptionController.ts
packages/consumption/src/modules/requests/incoming/IncomingRequestsController.ts
packages/consumption/test/modules/requests/IncomingRequestsController.test.ts
packages/consumption/test/modules/requests/RequestsIntegrationTest.ts

-   [ ] I ensured that the PR title is good enough for the changelog.

Remove unused Template resolver from IncomingRequestsController

---

.ci/runChecks.sh
packages/runtime/src/modules/DeciderModule.ts
packages/runtime/src/useCases/consumption/attributes/GetRepositoryAttributes.ts

Remove circular dependency

---

packages/runtime/src/useCases/common/Schemas.ts
packages/runtime/src/useCases/transport/relationshipTemplates/GetRelationshipTemplates.ts
packages/runtime/src/useCases/transport/tokens/GetTokens.ts
packages/runtime/test/transport/relationshipTemplates.test.ts
packages/runtime/test/transport/tokens.test.ts

-   [X] I added/updated tests.
-   [X] I ensured that the PR title is good enough for the changelog.

Allow filtering by personalization

---

.github/workflows/publish.yml
.github/workflows/test.yml

As the [publish issues with node 23 are now fixed](https://github.com/npm/cli/issues/7853#issuecomment-2443991430) when using Node.js `>=23.1.0` and [the connector is bumped to node 23](https://github.com/nmshd/connector/pull/298) we should make sure our libs are working on this version.
Therefore all pipelines are bumped to node current again.

Bump Node.js version in pipelines

---

packages/runtime/src/extensibility/facades/transport/RelationshipsFacade.ts
packages/runtime/src/useCases/common/Schemas.ts
packages/runtime/src/useCases/transport/relationships/CanCreateRelationship.ts
packages/runtime/src/useCases/transport/relationships/index.ts
packages/runtime/test/transport/relationships.test.ts

A `templateId` and a `creationContent` are required to create a Relationship, but to check whether a Relationship can in principle be established to the creator of the RelationshipTemplate, it is sufficient to specify the `templateId`. For this reason, the `creationContent` parameter of the CanCreateRelationshipUseCase is now made optional. The `creationContent` parameter can still be added if additional validation of the `creationContent` is wanted.

Make `creationContent` parameter of CanCreateRelationshipUseCase optional

---

packages/runtime/src/useCases/common/Schemas.ts

The rearranging lets it look more severe in https://github.com/nmshd/runtime/pull/307/files#diff-85c87594e414aa5f153c37403b0dbd816f1a4d9773ba4fbe5cb4e988c6488854 than it actually is.

Re-generate schemas

---

packages/runtime/src/useCases/transport/relationships/CreateRelationship.ts

Remove unused injected controller

---

packages/runtime/src/useCases/common/Schemas.ts
packages/runtime/src/useCases/transport/files/UploadOwnFile.ts
packages/transport/src/modules/files/local/SendFileParameters.ts

Seems like this was possible under the hood all the time and just propagated wrong.

Allow passing no title and description when uploading a file

---

packages/app-runtime/test/lib/TestUtil.ts
packages/app-runtime/test/lib/natives/FakeNativeBootstrapper.ts
packages/app-runtime/test/modules/PushNotification.test.ts

When using one EventBus for the whole test we win the flexibility to just wait for the EventBus to being finished with processing and then we can do checks.

Simplify the PushNotificationModuleTest

---

package-lock.json
packages/transport/test/modules/relationships/RelationshipsController.test.ts
packages/transport/test/testHelpers/TestUtil.ts

It is now possible to test in the Transport library that a Relationship cannot be created after the RelationshipTemplate has been loaded if the creator of the RelationshipTemplate has deleted its Identity in the meantime.

Cannot create Relationship to deleted creator of RelationshipTemplate

---

packages/app-runtime/test/runtime/Startup.test.ts
packages/runtime/src/extensibility/facades/transport/IdentityDeletionProcessesFacade.ts
packages/runtime/src/useCases/common/Schemas.ts
packages/runtime/src/useCases/transport/identityDeletionProcesses/InitiateIdentityDeletionProcess.ts
packages/runtime/test/transport/account.test.ts

I discussed this with @tnotheis and it's the best possibility for testing this feature end to end without having to adjust the backbone for every test. We see minimal to no attack vector to this as we simple cannot use this and an attacker could use this anyways by just calling the backbone manually.
As a cherry on top this makes our tests way more readable!

Expose setting the length of the grace period when initiating an IdentityDeletionProcess

---

packages/app-runtime/test/runtime/AppStringProcessor.test.ts
packages/runtime/src/extensibility/facades/transport/DevicesFacade.ts
packages/runtime/test/transport/account.test.ts

Rename getDeviceOnboardingToken to createDeviceOnboardingToken

---

packages/transport/src/modules/accounts/AccountController.ts
packages/transport/src/modules/sync/SynchronizedCollection.ts

Add debug log for SynchronizedCollection in CI runs for database writes with outdated data

---

packages/runtime/src/modules/DeciderModule.ts
packages/runtime/src/modules/decide/RequestConfig.ts
packages/runtime/test/modules/DeciderModule.test.ts

Also, `owner` is removed from `ProposeAttributeRequestItemConfig` since it can only be the recipient anyway.
There remain problems with the `owner` of a CreateAttributeRequestItem and ReadAttributeRequestItem, because an empty strings needs to be converted to the address of the recipient. However, I'll tackle these issues in a separate PR.

RequestConfig is skipped if false is configured as value

---

packages/transport/src/modules/sync/SynchronizedCollection.ts

Improve pipeline debug logging for SynchronizedCollection data inconsistencies

---

packages/app-runtime/src/AppStringProcessor.ts
packages/app-runtime/src/extensibility/ui/IUIBridge.ts
packages/app-runtime/test/lib/FakeUIBridge.ts
packages/app-runtime/test/lib/MockUIBridge.matchers.ts
packages/app-runtime/test/lib/MockUIBridge.ts
packages/app-runtime/test/runtime/AppStringProcessor.test.ts

Retry processing password protected references for wrong passwords

---

packages/consumption/src/modules/attributes/AttributesController.ts
packages/consumption/src/modules/common/flattenObject.ts
packages/consumption/src/modules/common/index.ts
packages/consumption/src/modules/requests/itemProcessors/createAttribute/CreateAttributeRequestItemProcessor.ts
packages/runtime/src/useCases/consumption/attributes/CreateRepositoryAttribute.ts

I moved this to a lower level to be able to reuse it. This is advantageous for preventing the creation of duplicate RepositoryAttributes via a Request. Also, it allows to implement a CanCreateRepositoryAttribute use case more easily.

Move check for RepositoryAttribute duplicates to AttributesController

---

packages/app-runtime/src/AppConfig.ts
packages/app-runtime/src/AppRuntime.ts
packages/app-runtime/src/natives/INativeConfigAccess.ts
packages/app-runtime/test/lib/TestUtil.ts
packages/app-runtime/test/lib/natives/FakeNativeConfigAccess.ts

This PR massively simplifies how to configure the app runtime:
Old:
- setup the native config access
- the native config access tries to resolve many things from the app
- some keys were read from the config acess
New:
- just pass the config to the runtime before startup

Make app-runtime modules configurable and simplfy the app-runtime startup

---

packages/runtime/src/dataViews/DataViewExpander.ts

i18n in flutter is json based, and a leaf can not be a branch:
Current usage would need to define such a json:
```
{
"dvo": {
"identity": {
"unknown": "a translation",
"unknown": {
"description": "another translation"
}
}
}
}
```
which results in a `Duplicate object key` warning. As the description is not used for unknown identities and the leaf was not definable I just made name = description to fix this.

Wrong i18n usage

---

packages/app-runtime/src/multiAccount/MultiAccountController.ts
packages/app-runtime/test/runtime/Onboarding.test.ts

This was designed - but completely forgotten. The app has some pretty ugly issues when scanning a "burned" token, so this is long overdue.

The recovery kit token is not deleted from the backbone after successful onboarding

---

packages/app-runtime/src/modules/appEvents/RelationshipTemplateProcessedModule.ts
packages/app-runtime/test/lib/MockUIBridge.matchers.ts
packages/app-runtime/test/lib/TestUtil.ts
packages/app-runtime/test/modules/appEvents/RelationshipTemplateProcessedModule.test.ts
packages/runtime/src/events/consumption/RelationshipTemplateProcessedEvent.ts
packages/runtime/src/modules/RequestModule.ts

The RequestModule creates expired requests in the `PeerRelationshipTemplateLoaded` event handler

---

packages/consumption/test/modules/requests/itemProcessors/createAttribute/CreateAttributeRequestItemProcessor.test.ts

Make CreateAttributeRequestItemProcessor tests independent

---

packages/consumption/src/modules/attributes/AttributesController.ts
packages/runtime/src/useCases/common/RuntimeErrors.ts
packages/runtime/src/useCases/consumption/attributes/NotifyPeerAboutRepositoryAttributeSuccession.ts
packages/runtime/test/consumption/attributes.test.ts

Example: An Identity has a RepositoryAttribute and shared it with a peer, but the peer deleted the peer shared Attribute. As a result, the Identity has an own shared IdentityAttribute with `deletionInfo.deletionStatus = DeletedByPeer`. Then, the peer asks for that RepositoryAttribute again and the Identity shares it again. Now, the Identity has two own shared IdentityAttributes, one with deletionInfo and one without it. If the Identity then succeeds the RepositoryAttribute and wants to notify about the succession, it is necessary to chose the own shared IdentityAttribute without deletionInfo as predecessor.

Notifying about RepositoryAttribute succession isn't possible if additional own shared IdentityAttribute with deletionInfo exsists

---

packages/consumption/src/modules/attributes/AttributesController.ts
packages/runtime/src/dataViews/DataViewExpander.ts
packages/runtime/src/useCases/common/Schemas.ts
packages/runtime/src/useCases/consumption/attributes/GetAttributes.ts
packages/runtime/src/useCases/consumption/attributes/GetOwnSharedAttributes.ts
packages/runtime/src/useCases/consumption/attributes/GetPeerSharedAttributes.ts

Because of merging PR https://github.com/nmshd/runtime/pull/420, the parameter `onlyValid` of the `getLocalAttributes` method of the AttributesController is no longer needed.

Remove `onlyValid` params

---

packages/content/src/attributes/IdentityAttribute.ts
packages/content/src/attributes/IdentityAttributeQuery.ts

This allows tags like `urn:xbildung-de:destatis:codeliste:artdesschulabschlusses=http://xbildung.de/def/destatis/1.0/code/artdesschulabschlusses/allgemeine_hochschulreife`

Allow longer tags

---

packages/content/src/requests/RequestItem.ts
packages/content/src/requests/items/authentication/AuthenticationRequestItem.ts
packages/content/src/requests/items/formField/FormFieldRequestItem.ts
packages/content/test/requests/Request.test.ts
packages/runtime/src/dataViews/DataViewExpander.ts
packages/runtime/src/modules/decide/RequestConfig.ts
packages/runtime/src/useCases/common/Schemas.ts
packages/runtime/src/useCases/consumption/attributes/CreateAndShareRelationshipAttribute.ts
packages/runtime/src/useCases/consumption/attributes/ShareRepositoryAttribute.ts
packages/runtime/test/consumption/attributes.test.ts
packages/runtime/test/modules/DeciderModule.test.ts

Remove `title` from RequestItem

---

packages/consumption/src/modules/attributes/AttributesController.ts
packages/consumption/src/modules/requests/itemProcessors/createAttribute/CreateAttributeRequestItemProcessor.ts
packages/consumption/src/modules/requests/itemProcessors/proposeAttribute/ProposeAttributeRequestItemProcessor.ts
packages/consumption/src/modules/requests/itemProcessors/readAttribute/ReadAttributeRequestItemProcessor.ts
packages/consumption/src/modules/requests/itemProcessors/shareAttribute/ShareAttributeRequestItemProcessor.ts
packages/consumption/test/modules/requests/itemProcessors/proposeAttribute/ProposeAttributeRequestItemProcessor.test.ts
packages/consumption/test/modules/requests/itemProcessors/readAttribute/ReadAttributeRequestItemProcessor.test.ts
packages/consumption/test/modules/requests/itemProcessors/shareAttribute/ShareAttributeRequestItemProcessor.test.ts
packages/runtime/src/useCases/consumption/attributes/CanCreateRepositoryAttribute.ts

Using validateTagsForType it's much easier to validate the tags of a File, because it is not necessary to create a draft Attribute.

Add validateTagsForType

---

packages/runtime/src/dataViews/DataViewExpander.ts
packages/runtime/src/dataViews/transport/FileDVO.ts
packages/runtime/test/dataViews/requestItems/TransferFileOwnershipRequestItemDVO.test.ts

`truncatedReference` is removed b/c the app doesn't need that value and it seems to be broken anyways.

Update the FileDVO to contain `reference.truncated` and `reference.url`

---

packages/app-runtime/src/AppStringProcessor.ts
packages/app-runtime/test/runtime/AppStringProcessor.test.ts
packages/core-types/src/references/Reference.ts
packages/core-types/test/references/Reference.test.ts

To route from the document hosted at `https://backbone.example.com/r/ID#12345` to the app we need to accept `nmshds://backbone.example.com/r/ID#12345` to be processed from the apps. Each app will only listen on their personal backbone.

Allow url references with `nmshd(s)` schema

---

packages/app-runtime/src/AppStringProcessor.ts

`processDeviceOnboardingReference` is throwing when getting an invalid reference

---

packages/consumption/src/consumption/ConsumptionCoreErrors.ts

The `error.consumption.requests.cannotSetWasAutomaticallyDecided` error code was needed in the first version of Runtime PR https://github.com/nmshd/runtime/pull/568. However, in the final merged version, it wasn't needed anymore which is why it can be removed now.

Unused `cannotSetWasAutomaticallyDecided` error code

---

packages/runtime/src/useCases/common/Schemas.ts
packages/runtime/src/useCases/consumption/requests/GetIncomingRequests.ts

As the property `wasAutomaticallyDecided` was added to the LocalRequest in PR https://github.com/nmshd/runtime/pull/568, it can be added as query parameter to the use case for querying incoming Requests as well.

Add `wasAutomaticallyDecided` query parameter to use case for querying incoming Requests

---

packages/consumption/src/modules/requests/itemProcessors/transferFileOwnership/TransferFileOwnershipRequestItemProcessor.ts
packages/consumption/test/modules/requests/itemProcessors/transferFileOwnership/TransferFileOwnershipRequestItemProcessor.test.ts
packages/content/src/requests/items/transferFileOwnership/TransferFileOwnershipRequestItem.ts
packages/content/test/requests/items/TransferFileOwnershipRequestItem.test.ts
packages/runtime/src/dataViews/content/RequestItemDVOs.ts
packages/runtime/src/useCases/common/Schemas.ts
packages/runtime/test/modules/DeciderModule.test.ts

The ownership of the original File might not be transferred using a TransferFileOwnershipRequestItem

---

packages/runtime/test/lib/testUtils.ts
packages/runtime/test/transport/files.test.ts

This came up while adding `wasViewedAt` for Files and testing the query (https://github.com/nmshd/runtime/pull/611).

Make Files tests independent

---

packages/consumption/src/modules/requests/incoming/IncomingRequestsController.ts
packages/consumption/src/modules/requests/outgoing/OutgoingRequestsController.ts

Before #612 there could be multiple requests with the same ID. This can cause an endless loop when those requests are queried. With this fix we stop this endless loop.

Endless loop when updating request expiry

---

packages/transport/src/core/TransportCoreErrors.ts
packages/transport/src/modules/accounts/AccountController.ts

needed for 
https://github.com/nmshd/connector/pull/343

The error for missing identity on startup is not machine readable

---

packages/app-runtime/src/AppStringProcessor.ts
packages/app-runtime/test/runtime/AppStringProcessor.test.ts

I deleted this functionality in #750 but we need it to scan recovery kits.

Re-add `processDeviceOnboardingReference` to the AppStringProcessor

---

packages/consumption/src/modules/attributes/AttributesController.ts
packages/consumption/test/modules/attributes/AttributesController.test.ts
packages/runtime/src/useCases/common/RuntimeErrors.ts
packages/runtime/src/useCases/consumption/attributes/DeleteAttributeAndNotify.ts
packages/runtime/test/consumption/attributes.test.ts

If we delete an Attribute, we also delete all its predecessors. Consequently, if we delete an Attribute that wasn't forwarded to a peer, but one of its predecessors was, we need to send a corresponding Notification to that peer.

Notify peers about Attribute deletion if only predecessor was shared

---

.github/renovate.json5

It's enabled in the connector repo - but not here .. weird.

Enable docker digest pinning for renovate

---

packages/runtime-types/src/transport/FileDTO.ts
packages/runtime/src/dataViews/DataViewExpander.ts
packages/runtime/src/dataViews/transport/FileDVO.ts
packages/runtime/src/useCases/transport/files/FileMapper.ts

The actual bug is then in the app where the creator is always displayed as the owner, which is not true if the file was transferred by a TransferFileOwnershipRI.

The File owner is not exposed in FileDTO and FileDVO
